server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #database_name postgres schema public
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: postgres # username
    password: postgres # user password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

app:
  test: Connection is working...

client:
  cards:
    endpoint: http://localhost:9091
  loans:
    endpoint: http://localhost:9093